/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SSDI_Lab05;

import javafx.application.Application;
import javafx.beans.property.DoubleProperty;
import javafx.beans.property.FloatProperty;
import javafx.beans.property.SimpleFloatProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;
import javafx.collections.ObservableList;
import javafx.scene.Scene;
import javafx.scene.chart.PieChart.Data;
import javafx.scene.control.*;
import javafx.stage.Stage;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.scene.layout.VBox;

public class StudentRecord extends Application {
    private StringProperty StudentID;
    private StringProperty letterGrade;
    private FloatProperty assignments;
    private FloatProperty midterm;
    private FloatProperty Final;
    private DoubleProperty mark;

    private String Studentnum;
    private String letter;
    private Float assignmentgrade;
    private Float midtermexam;
    private Float Finalexam;
    private Double fmark;


    public StudentRecord(String sid, Float mid, Float assign, Float fin){
        this.StudentID = new SimpleStringProperty(sid);
        this.Final = new SimpleFloatProperty(fin);
        this.assignments = new SimpleFloatProperty(assign);
        this.midterm = new SimpleFloatProperty(mid);

    }
    /* public StringProperty StudentIDProperty(){
        return StudentID;
    }
    public StringProperty letterGradeProperty(){
        return letterGrade;
    }
    public FloatProperty assignmentsProperty(){
        return assignments;
    }
    public FloatProperty midtermProperty(){
        return midterm;
    }
    public FloatProperty FinalProperty(){
        return Final;
    }
    public DoubleProperty markProperty(){
        return mark;
    } */

    public String getStudentID() {
        return StudentID.get();
    }
    public void setStudentID(String fName) {
        StudentID.set(fName);
    }
    public Float getassignments() {
        return assignments.get();
    }
    public void setassignments(Float fName) {
        assignments.set(fName);
    }
    public Float getmidterm() {
        return midterm.get();
    }
    public void setmidterm(Float fName) {
        midterm.set(fName);
    }
    public Float getfinal() {
        return Final.get();
    }
    public void setfinal(Float fName) {
        Final.set(fName);
    }

    @Override
    public void start(Stage stage) {
        ObservableList<StudentRecord> data = DataSource.getAllMarks();
        TableView<StudentRecord> tableView = new TableView<StudentRecord>(data);

        TableColumn<StudentRecord, String> sidcol = new TableColumn<StudentRecord, String>("S.ID");
        sidcol.setCellValueFactory(new PropertyValueFactory<StudentRecord, String>("Studentnum"));
        
        tableView.getColumns().add(sidcol);

        TableColumn<StudentRecord, String> acol = new TableColumn<StudentRecord, String>("Assignments");
        acol.setCellValueFactory(new PropertyValueFactory<StudentRecord, String>("Studentnum"));
        
        tableView.getColumns().add(acol);

        TableColumn<StudentRecord, String> midcol = new TableColumn<StudentRecord, String>("Midterm");
        midcol.setCellValueFactory(new PropertyValueFactory<StudentRecord, String>("Studentnum"));
        
        tableView.getColumns().add(midcol);

        TableColumn<StudentRecord, String> fcol = new TableColumn<StudentRecord, String>("Final");
        fcol.setCellValueFactory(new PropertyValueFactory<StudentRecord, String>("Studentnum"));
        
        tableView.getColumns().add(fcol);

        TableColumn<StudentRecord, String> lcol = new TableColumn<StudentRecord, String>("Letter");
        lcol.setCellValueFactory(new PropertyValueFactory<StudentRecord, String>("Studentnum"));
        
        tableView.getColumns().add(lcol);

        TableColumn<StudentRecord, String> markcol = new TableColumn<StudentRecord, String>("Grade");
        markcol.setCellValueFactory(new PropertyValueFactory<StudentRecord, String>("Studentnum"));
        
        tableView.getColumns().add(markcol);

        
        VBox vbox = new VBox(tableView);

        Scene scene = new Scene(vbox, 700, 350);
        stage.setScene(scene);
        stage.setTitle("Lab5");
        stage.show();

    }

    public StudentRecord() {
    }

    public StudentRecord(String SID,
            float assign,
            float mid,
            float Fin) {
        this.Studentnum = SID;
        this.assignmentgrade = assign;
        this.midtermexam = mid;
        this.Finalexam = Fin;
        this.fmark = (0.2 * assignmentgrade) + (0.3 * midtermexam) + (0.5 * Finalexam);
        if (this.fmark >= 80) {
            this.letter= "A";
        } else if (this.fmark >= 70 && this.fmark < 80) {
            this.letter= "B";
        } else if (this.fmark >= 60 && this.fmark < 70) {
            this.letter = "C";
        } else if (this.fmark >= 50 && this.fmark < 60) {
            this.letter= "D";
        } else if (this.fmark < 50 && this.fmark >= 0) {
            this.letter = "F";
        }

    }

    public static void main(String[] args) {
        System.out.println(DataSource.getAllMarks());
        launch();
    }

}